#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "communication_interface.h" // generated by javah via maven-native-plugin

#include <errno.h>
#include <sys/utsname.h>


JNIEXPORT jint JNICALL Java_ts_java_jni_c_CInterface_uname
  (JNIEnv * env, jobject jobj)
{
	

   struct utsname buffer;

   errno = 0;
   if (uname(&buffer) != 0) {
      perror("uname");
      exit(EXIT_FAILURE);
   }

   printf("system name = %s\n", buffer.sysname);
   printf("node name   = %s\n", buffer.nodename);
   printf("release     = %s\n", buffer.release);
   printf("version     = %s\n", buffer.version);
   printf("machine     = %s\n", buffer.machine);

   #ifdef _GNU_SOURCE
      printf("domain name = %s\n", buffer.domainname);
   #endif

   return EXIT_SUCCESS;
	
}


